<a href="https://colab.research.google.com/github/hhharshitt/ML-Experiments/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Experiment-1 Basic Array Creation

In [ ]:
import numpy as np
my_list = [10, 20, 30, 40, 50]
arr = np.array(my_list)
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [ ]:
#Experiment-2 Zeros and Ones Matrices

In [ ]:
zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape of Zeros:", zeros_matrix.shape)
print("\nOnes Matrix:\n", ones_matrix)
print("Shape of Ones:", ones_matrix.shape)

Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Zeros: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape of Ones: (2, 5)


In [ ]:
#Expeiment-3 Reshaping Arrays

In [ ]:
original = np.arange(1, 13)
reshaped = original.reshape(3, 4)

print("Original Array:", original)
print("Original Shape:", original.shape)
print("\nReshaped Matrix:\n", reshaped)
print("Reshaped Shape:", reshaped.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [ ]:
#Experiment 4: Random Integers and Statistics

In [ ]:
rand_arr = np.random.randint(1, 101, 10)

print("Random Array:", rand_arr)
print("Min:", rand_arr.min())
print("Max:", rand_arr.max())
print("Mean:", rand_arr.mean())
print("Sum:", rand_arr.sum())

Random Array: [32 80 53 12 10 63  3 17  2 51]
Min: 2
Max: 80
Mean: 32.3
Sum: 323


In [ ]:
#Experiment 5: DataFrame from Dictionary

In [ ]:
import pandas as pd
data = {
    'Student Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Marks': [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print("DataFrame:\n", df)
print("\nColumn Data Types:\n", df.dtypes)

DataFrame:
   Student Name  Marks
0        Alice     85
1          Bob     92
2      Charlie     78
3        David     88

Column Data Types:
 Student Name    object
Marks            int64
dtype: object


In [ ]:
#Experiment 6: Head and Tail

In [ ]:
csv_content = """StudentID,Name,Math_Score,Science_Score,Attendance
101,Arjun,85,78,95
102,Deepa,92,85,98
103,Sanjay,,80,85
104,Aditi,88,92,90
105,Vijay,76,70,80
106,Manoj,95,,88
107,Neha,89,88,92
108,Rohan,,75,87
109,Priya,82,81,94
110,Amit,90,84,91"""

with open('data.csv', 'w') as f:
    f.write(csv_content)

In [ ]:
df = pd.read_csv('data.csv')

print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

First 5 records:
   StudentID    Name  Math_Score  Science_Score  Attendance
0        101   Arjun        85.0           78.0          95
1        102   Deepa        92.0           85.0          98
2        103  Sanjay         NaN           80.0          85
3        104   Aditi        88.0           92.0          90
4        105   Vijay        76.0           70.0          80

Last 5 records:
   StudentID   Name  Math_Score  Science_Score  Attendance
5        106  Manoj        95.0            NaN          88
6        107   Neha        89.0           88.0          92
7        108  Rohan         NaN           75.0          87
8        109  Priya        82.0           81.0          94
9        110   Amit        90.0           84.0          91


In [ ]:
#Experiment 7: Dataset Structure and Missing Values

In [ ]:
df = pd.read_csv('data.csv')
print("Dataset Information:")
df.info()
rows, cols = df.shape
missing_values = df.isnull().sum().sum()

print(f"\nRows: {rows}, Columns: {cols}")
print(f"Total Missing Values: {missing_values}")

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   StudentID      10 non-null     int64  
 1   Name           10 non-null     object 
 2   Math_Score     8 non-null      float64
 3   Science_Score  9 non-null      float64
 4   Attendance     10 non-null     int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 532.0+ bytes

Rows: 10, Columns: 5
Total Missing Values: 3


In [ ]:
#Experiment 8: Statistical Summary

In [ ]:
df = pd.read_csv('data.csv')
summary = df.describe()
print("Statistical Summary:\n", summary)

Statistical Summary:
        StudentID  Math_Score  Science_Score  Attendance
count   10.00000    8.000000       9.000000   10.000000
mean   105.50000   87.125000      81.444444   90.000000
std      3.02765    6.010408       6.710274    5.249339
min    101.00000   76.000000      70.000000   80.000000
25%    103.25000   84.250000      78.000000   87.250000
50%    105.50000   88.500000      81.000000   90.500000
75%    107.75000   90.500000      85.000000   93.500000
max    110.00000   95.000000      92.000000   98.000000
